typedef struct {
    const char *kw;
    const char *enc;
} Keyword;

/*
 * Keyword encodings as per:
 * http://www.riscos.com/support/developers/bbcbasic/appendices/minabbreviations.html
 */
Keyword keywords[] = {
    {"ABS"        ,"\x94"},
    {"ACS"        ,"\x95"},
    {"ADVAL"      ,"\x96"},
    {"AND"        ,"\x80"},
    {"APPEND"     ,"\xC7\x8E"},
    {"ASC"        ,"\x97"},
    {"ASN"        ,"\x98"},
    {"ATN"        ,"\x99"},
    {"AUTO"       ,"\xC7\x8F"},
    {"BEAT"       ,"\xC6\x8F"},
    {"BEATS"      ,"\xC8\x9E"},
    {"BGET"       ,"\x9A"},
    {"BPUT"       ,"\xD5"},
//  {"BY"         ,"\x42\x59"}, // NOT TOKENISED
    {"CALL"       ,"\xD6"},
    {"CASE"       ,"\xC8\x8E"},
    {"CHAIN"      ,"\xD7"},
    {"CHR"        ,"\xBD"},
    {"CIRCLE"     ,"\xC8\x8F"},
    {"CLEAR"      ,"\xD8"},
    {"CLG"        ,"\xDA"},
    {"CLOSE"      ,"\xD9"},
    {"CLS"        ,"\xDB"},
    {"COLOR"      ,"\xFB"},
    {"COLOUR"     ,"\xFB"},
    {"COS"        ,"\x9B"},
    {"COUNT"      ,"\x9C"},
    {"CRUNCH"     ,"\xC7\x90"},
    {"DATA"       ,"\xDC"},
    {"DEF"        ,"\xDD"},
    {"DEG"        ,"\x9D"},
    {"DELETE"     ,"\xC7\x91"},
    {"DIM"        ,"\xDE"},
    {"DIV"        ,"\x81"},
    {"DRAW"       ,"\xDF"},
    {"EDIT"       ,"\xC7\x92"},
    {"EDITO"      ,"\xC7\x92\x4F"},
    {"ELLIPSE"    ,"\xC8\x9D"},
    {"ELSE"       ,"\xCC"},
    {"END"        ,"\xE0"},
    {"ENDCASE"    ,"\xCB"},
    {"ENDIF"      ,"\xCD"},
    {"ENDPROC"    ,"\xE1"},
    {"ENDWHILE"   ,"\xCE"},
    {"EOF"        ,"\xC5"},
    {"EOR"        ,"\x82"},
    {"ERL"        ,"\x9E"},
    {"ERR"        ,"\x9F"},
    {"ERROR"      ,"\x85"},
    {"EVAL"       ,"\xA0"},
    {"EXP"        ,"\xA1"},
    {"EXT"        ,"\xA2"},
    {"FALSE"      ,"\xA3"},
    {"FILL"       ,"\xC8\x90"},
    {"FN"         ,"\xA4"},
    {"FOR"        ,"\xE3"},
    {"GCOL"       ,"\xE6"},
    {"GET"        ,"\xA5"},
    {"GET"        ,"\xBE"},
    {"GOSUB"      ,"\xE4"},
    {"GOTO"       ,"\xE5"},
    {"HELP"       ,"\xC7\x93"},
    {"HIMEM"      ,"\xD3"},
    {"HIMEM"      ,"\x93"},
    {"IF"         ,"\xE7"},
    {"INKEY"      ,"\xA6"},
    {"INKEY"      ,"\xBF"},
    {"INPUT"      ,"\xE8"},
    {"INSTALL"    ,"\xC8\x9A"},
    {"INSTR"      ,"\xA7"},
    {"INT"        ,"\xA8"},
    {"LEFT"       ,"\xC0"},
    {"LEN"        ,"\xA9"},
    {"LET"        ,"\xE9"},
    {"LIBRARY"    ,"\xC8\x9B"},
    {"LINE"       ,"\x86"},
    {"LIST"       ,"\xC7\x94"},
    {"LISTO"      ,"\xC7\x94\x4F"},
    {"LN"         ,"\xAA"},
    {"LOAD"       ,"\xC7\x95"},
    {"LOCAL"      ,"\xEA"},
    {"LOG"        ,"\xAB"},
    {"LOMEM"      ,"\xD2"},
    {"LOMEM"      ,"\x92"},
    {"LVAR"       ,"\xC7\x96"},
    {"MID"        ,"\xC1"},
    {"MOD"        ,"\x83"},
    {"MODE"       ,"\xEB"},
    {"MOUSE"      ,"\xC8\x97"},
    {"MOVE"       ,"\xEC"},
    {"NEW"        ,"\xC7\x97"},
    {"NEXT"       ,"\xED"},
    {"NOT"        ,"\xAB"},
    {"OF"         ,"\xCA"},
    {"OFF"        ,"\x87"},
    {"OLD"        ,"\xC7\x98"},
    {"ON"         ,"\xEE"},
    {"OPENIN"     ,"\x8E"},
    {"OPENOUT"    ,"\xAE"},
    {"OPENUP"     ,"\xAD"},
    {"OR"         ,"\x84"},
    {"ORIGIN"     ,"\xC8\x91"},
    {"OSCLI"      ,"\xFF"},
    {"OTHERWISE"  ,"\x7F"},
    {"OVERLAY"    ,"\xC8\xA3"},
    {"PAGE"       ,"\xD0"},
    {"PAGE"       ,"\x90"},
    {"PI"         ,"\xAF"},
    {"PLOT"       ,"\xF0"},
    {"POINT"      ,"\xC8\x92"},
    {"POINT"      ,"\xB0"},
    {"POS"        ,"\xB1"},
    {"PRINT"      ,"\xF1"},
    {"PROC"       ,"\xF2"},
    {"PTR"        ,"\xCF"},
    {"PTR"        ,"\x8F"},
    {"QUIT"       ,"\xC8\x98"},
    {"READ"       ,"\xF3"},
    {"RECTANGLE"  ,"\xC8\x93"},
    {"REM"        ,"\xF4"},
    {"RENUMBER"   ,"\xC7\x99"},
    {"REPEAT"     ,"\xF5"},
    {"REPORT"     ,"\xF6"},
    {"REPORT"     ,"\xF6\x24"},
    {"RESTORE"    ,"\xF7"},
    {"RETURN"     ,"\xF8"},
    {"RIGHT"      ,"\xC2"},
    {"RND"        ,"\xB3"},
    {"RUN"        ,"\xF9"},
    {"SAVE"       ,"\xC7\x9QA"},
    {"SGN"        ,"\xB4"},
    {"SIN"        ,"\xB5"},
    {"SOUND"      ,"\xD4"},
    {"SPC"        ,"\x89"},
    {"SQR"        ,"\xB6"},
    {"STEP"       ,"\x88"},
    {"STEREO"     ,"\xC8\xA2"},
    {"STOP"       ,"\xFA"},
    {"STR"        ,"\xC3"},
    {"STRING"     ,"\xC4"},
    {"SUM"        ,"\xC6\x8E"},
    {"SUMLEN"     ,"\xC6\x8E"},
    {"SWAP"       ,"\xC8\x94"},
    {"SYS"        ,"\xC8\x99"},
    {"TAB"        ,"\x8A"},
    {"TAN"        ,"\xB7"},
    {"TEMPO"      ,"\xC8\x9F"},
    {"TEXTLOAD"   ,"\xC7\x9B"},
    {"TEXTSAVE"   ,"\xC7\x9C"},
    {"THEN"       ,"\x8C"},
    {"TIME"       ,"\xD1"},
    {"TIME"       ,"\x91"},
    {"TINT"       ,"\xC8\x9C"},
    {"TO"         ,"\xB8"},
    {"TOP"        ,"\xB8\x50"},
    {"TRACE"      ,"\xFC"},
    {"TRUE"       ,"\xB9"},
    {"TWIN"       ,"\xC7\x9D"},
    {"TWINO"      ,"\xC7\x9E"},
    {"UNTIL"      ,"\xFD"},
    {"USR"        ,"\xBA"},
    {"VAL"        ,"\xBB"},
    {"VDU"        ,"\xEF"},
    {"VOICE"      ,"\xC8\xA1"},
    {"VOICES"     ,"\xC8\xA0"},
    {"VPOS"       ,"\xBC"},
    {"WAIT"       ,"\xC8\x96"},
    {"WHEN"       ,"\xC9"},
    {"WHILE"      ,"\xC8\x95"},
    {"WIDTH"      ,"\xFE"},
    {NULL, NULL}
};

const char* kw_decode(uint8_t* buf, size_t* kw_len, size_t* kwenc_len) {
    for (size_t i = 0; keywords[i].kw != NULL; ++i) {
        Keyword *kw = &keywords[i];
        *kwenc_len = strlen(kw->enc);
        if (!strncmp((const char*)buf, kw->enc, *kwenc_len)) {
            *kw_len = strlen(kw->kw);
            return kw->kw;
        }
    }

    return NULL;
}

const char* kw_encode(uint8_t* buf) {
    for (size_t i = 0; keywords[i].kw != NULL; ++i) {
        Keyword *kw = &keywords[i];
        if (!strcmp((const char*)buf, kw->kw)) {
            return kw->enc;
        }
    }

    return NULL;
}
